/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Ramu Sharma
 */
public class CreatePreference extends javax.swing.JFrame {
    String path;
    boolean octave = false;
    boolean octaveCheck = false;
    String[] letters = {"C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"};//C
    int cnt = 1;
    int octave1, octave2;
    int octaveDif = 0;
    int octaveCount = 0;
    int begNote, endNote;

    File f;
    FileWriter fw;
    BufferedWriter bw;
    /**
     * Creates new form CreatePreference
     */
    public CreatePreference() {
        initComponents();
        
        checkButton.setOpaque(false);
        checkButton.setContentAreaFilled(false);
        checkButton.setBorderPainted(false);
        
        cancelButton.setOpaque(false);
        cancelButton.setContentAreaFilled(false);
        cancelButton.setBorderPainted(false);
        
        setNotes.setOpaque(false);
        setNotes.setContentAreaFilled(false);
        setNotes.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();
        fileDest = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        instructions = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        firstNote = new javax.swing.JComboBox<>();
        setNotes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastNote = new javax.swing.JComboBox<>();
        fileName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        displayArea.setColumns(20);
        displayArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        displayArea.setLineWrap(true);
        displayArea.setRows(5);
        displayArea.setBorder(null);
        displayArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayAreaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                displayAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(displayArea);

        fileDest.setBackground(new java.awt.Color(0, 0, 0));
        fileDest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fileDest.setForeground(new java.awt.Color(255, 255, 255));
        fileDest.setText("Enter File Name:");

        checkButton.setBackground(new java.awt.Color(0, 0, 0));
        checkButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        checkButton.setForeground(new java.awt.Color(255, 255, 255));
        checkButton.setText("Check");
        checkButton.setContentAreaFilled(false);
        checkButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setContentAreaFilled(false);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        instructions.setEditable(false);
        instructions.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        instructions.setText("Choose the first and last note of your Preference. Keep in mind the number of keys on your keyboard while doing this. Click on hte Set Notes button when you are done. Complete this step before choosing the octaves.");
        jScrollPane2.setViewportView(instructions);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        firstNote.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        firstNote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B" }));

        setNotes.setBackground(new java.awt.Color(0, 0, 0));
        setNotes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        setNotes.setForeground(new java.awt.Color(255, 255, 255));
        setNotes.setText("Set Notes");
        setNotes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNotesActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Note");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Note");

        lastNote.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lastNote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(firstNote, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNote, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(setNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(setNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fileName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fileDest)
                        .addGap(18, 18, 18)
                        .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileDest, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addGap(14, 14, 14)))
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        try{
            path = System.getProperty("user.dir") + "\\UserPreferences\\" + fileName.getText() + ".txt";
            File f = new File (path);
            f.createNewFile();
        }
        catch (IOException e){
            System.out.println(e);
        }
        
        displayArea.setText("");
        displayArea.setText("Enter octave number of the first key, and then press Control: ");
    }//GEN-LAST:event_checkButtonActionPerformed

    private void displayAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayAreaKeyTyped
        
    }//GEN-LAST:event_displayAreaKeyTyped

    private void displayAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayAreaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SHIFT && octave){
            if (octaveDif == 0 && cnt == endNote+1){
                displayArea.setEnabled(false);
                SaveInFile();
            }
            
            if (cnt == letters.length){
                cnt = 0;
                octaveDif--;
                System.out.println("octave dif " + octaveDif);
            }
            
            displayArea.append("\n");
            displayArea.append("Input key for " + letters[cnt] + ": ");
            cnt++;
        }
        if (evt.getKeyCode() == KeyEvent.VK_CONTROL && !octave){
            GetOctave();
        }
    }//GEN-LAST:event_displayAreaKeyPressed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Home h = new Home();
        this.setVisible(false);
        h.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void setNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNotesActionPerformed
        cnt = firstNote.getSelectedIndex();
        begNote = firstNote.getSelectedIndex();
        endNote = lastNote.getSelectedIndex();
        instructions.setText("Notes Set. Now type in the octaves and follow the rest of the instructions.");
    }//GEN-LAST:event_setNotesActionPerformed

    private void SaveInFile(){
        try{
            path = System.getProperty("user.dir") + "\\UserPreferences\\" + fileName.getText() + ".txt";
            f = new File (path);
            
            fw = new FileWriter(f, true);
            bw = new BufferedWriter (fw);
            
            displayArea.setCaretPosition(0);
            String[] lines = displayArea.getText().split("\\n");
            int linesIndex = 0;
            int arrStart;
            String in = "";
            int note1 = begNote;
            
            for (octaveDif = octave2 - octave1; octaveDif>=0; octaveDif--){
                for (arrStart = note1; arrStart <= 11; arrStart ++){
                    int temp = lines[linesIndex].lastIndexOf(":");
                    in = lines[linesIndex].substring(temp + 1);
                    System.out.println(in);
                    bw.append(letters[arrStart] + " " + in.trim());
                    bw.newLine();
                    linesIndex++;
                    if (octaveDif == 0 && arrStart == endNote){
                        break;
                    }
                }
                note1 = 0;
            }
            bw.flush();
            bw.close();
            
            Home h = new Home();
            h.begNote = begNote;
            h.endNote = endNote;
            this.setVisible(false);
            h.setVisible(true);
        }
        catch (IOException e){
            System.out.println(e);
        }
    }
    
    public void GetOctave(){
        int index;
        String oct = "";
        try{
            path = System.getProperty("user.dir") + "\\UserPreferences\\" + fileName.getText() + ".txt";
            f = new File (path);
            f.createNewFile();
            
            if (!octaveCheck){
                fw = new FileWriter(f);
            }
            else{
                fw = new FileWriter(f, true);
            }
            bw = new BufferedWriter (fw);
            
            displayArea.setCaretPosition(0);
            String line = displayArea.getText();
            index = line.lastIndexOf(":");
            oct = line.substring(index + 1).trim();
            bw.write("Octave" + oct);
            bw.newLine();
            bw.flush();
            bw.close();
        }
        catch (IOException e){
            System.out.println(e);
        }
        
        if (!octaveCheck){
            displayArea.setText("");
            displayArea.setText("Enter octave number of the last key, and then press Control: ");
            octave1 = Integer.parseInt(oct);
            octaveCheck = true;
        }
        else{
            octave = true;
            octave2 = Integer.parseInt(oct);
            octaveDif = octave2 - octave1;
            System.out.println(octaveDif);
            
            displayArea.setText("");
            instructions.setText("Enter the key that correspons to the note displayed. After every key entered, press Shift.");
            displayArea.append("Input key for " + letters[cnt] + ": ");
            cnt++;
        }
    }
    
    public void displayInstructions(){
        displayArea.append("Enter preferred file name above. Click check to create the file if it doesnt already exist, or edit an existing preference if it exists, and follow the next instruction.\n");
        instructions.setText("Choose the first and last note of your Preference. Keep in mind the number of keys on your keyboard while doing this. Click on hte Set Notes button when you are done. Complete this step before choosing the octaves.");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePreference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePreference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePreference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePreference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePreference().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JTextArea displayArea;
    private javax.swing.JLabel fileDest;
    private javax.swing.JTextField fileName;
    private javax.swing.JComboBox<String> firstNote;
    private javax.swing.JTextPane instructions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> lastNote;
    private javax.swing.JButton setNotes;
    // End of variables declaration//GEN-END:variables
}
